// Renders a chase-cam shot of each map and writes src/ui/mapThumbs.ts (inline data URIs). map-thumbs.ts
import { chromium } from 'playwright';
import fs from 'fs';
const b = await chromium.launch({ executablePath: process.env.CHROME || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await b.newPage({ viewport: { width: 640, height: 360 } });
await page.addInitScript('window.__name = (f) => f');
await page.goto('http://localhost:5173/');
await page.waitForFunction(() => (window as any).__app);
await page.addStyleTag({ content: '#hud, .hud, #ui > * { visibility: hidden !important }' });
const out: Record<string, string> = {};
for (const [id, tod, veh] of [['city', 'dusk', 'zr1'], ['country', 'day', 'zr1'], ['forest', 'day', 'zr1']] as const) {
  await page.evaluate(([id, tod, veh]) => {
    const a = (window as any).__app; (window as any).__forceSeed = 5;
    a.save.data.settings.weather = 'clear'; a.save.data.settings.timeOfDay = tod; a.save.data.settings.difficulty = 1;
    a.startGame(id, veh); const g = a.game; g.startCrash = () => undefined; g.fuel = 1; a.advance(3.2, 1 / 30);
    for (let i = 0; i < 150; i++) { g.player.phys.v = 38; a.advance(1 / 30, 1 / 30); }
  }, [id, tod, veh]);
  await page.waitForTimeout(800);
  const buf = await page.screenshot({ type: 'jpeg', quality: 72 });
  fs.writeFileSync(`/tmp/claude-0/thumb-${id}.jpg`, buf);
  out[id] = 'data:image/jpeg;base64,' + buf.toString('base64');
  console.log(id, buf.length);
}
fs.writeFileSync('src/ui/mapThumbs.ts', `// generated by scripts/map-thumbs.ts: a real in-game shot of each map for the map cards\nexport const MAP_THUMBS: Record<string, string> = ${JSON.stringify(out, null, 1)};\n`);
await b.close();
