// Gamepad rebinding: fake a controller, rebind Accelerate to button A and steer-left to right stick left, then drive with it.
import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: process.env.CHROME || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await b.newPage({ viewport: { width: 1280, height: 720 } });
await page.addInitScript(`window.__name = (f) => f;
window.__pad = { buttons: Array.from({ length: 17 }, () => ({ pressed: false, value: 0 })), axes: [0, 0, 0, 0], connected: true, id: 'fake', index: 0, mapping: 'standard' };
navigator.getGamepads = () => [window.__pad];`);
const errors: string[] = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('http://localhost:5173/');
await page.waitForFunction(() => (window as any).__app);
const press = (i: number, on: boolean) => page.evaluate(([i, on]) => { const p = (window as any).__pad; p.buttons[i as number] = { pressed: on as boolean, value: on ? 1 : 0 }; }, [i, on]);
const axis = (i: number, v: number) => page.evaluate(([i, v]) => { (window as any).__pad.axes[i as number] = v; }, [i, v]);
await page.evaluate(() => (window as any).__app.ui.show('settings'));
const btn = (a: string) => `#settings button[data-b="${a}"][data-i="2"]`;
const label = (a: string) => page.textContent(btn(a));
console.log('before:', await label('throttle'), '|', await label('left'));
await page.click(btn('throttle'));
console.log('waiting:', await label('throttle'));
await page.waitForTimeout(200);
await press(0, true); await page.waitForTimeout(1500); await press(0, false);
console.log('after rebind throttle -> A:', await label('throttle'), '| handbrake (had A):', await label('handbrake'));
await page.click(btn('left'));
await page.waitForTimeout(200);
await axis(2, -1); await page.waitForTimeout(1500); await axis(2, 0);
console.log('after rebind left -> right stick left:', await label('left'), '| leanLeft (had it):', await label('leanLeft'));
const saved = await page.evaluate(() => JSON.stringify((window as any).__app.save.data.settings.padBindings));
console.log('saved:', saved);
// drive: A now accelerates
await page.evaluate(() => { const a = (window as any).__app; a.ui.h.back(); a.startGame('city', 'r6'); a.advance(3.2); });
await press(0, true);
const v = await page.evaluate(async () => { const a = (window as any).__app; a.game.player.phys.v = 5; const v0 = a.game.player.phys.v; a.advance(2); return [v0, a.game.player.phys.v]; });
await press(0, false);
console.log('speed with A held:', v.map((x: number) => x.toFixed(1)).join(' -> '));
await axis(2, -1);
const st = await page.evaluate(() => { const a = (window as any).__app; a.advance(0.3); return a.game.input.steer.toFixed(2); });
console.log('steer with rebound stick:', st);
console.log('errors:', errors.length ? errors : 'none');
await b.close();
